---
name: Integration tests on Fabric DW
on:
  workflow_dispatch:
  pull_request:
    branches:
      - forked-version
  push:
    branches:
      - forked-version

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  integration-tests-fabric-dw:
    name: Regular
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        msodbc_version: ["17", "18"]

    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/${{ github.repository }}:CI-${{ matrix.python_version }}-msodbc${{ matrix.msodbc_version }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Run functional tests
        env:
          FABRIC_TEST_ENDPOINT: ${{ secrets.DBT_AZURESQL_SERVER }}
          FABRIC_TEST_DWH_NAME: ${{ secrets.DBT_AZURESQL_DB }}
        run: pytest -ra -v tests/functional
