---
name: Lint and Format
on:
  push:
    branches:
      - forked-version
  pull_request:
    branches:
      - forked-version

jobs:
  lint-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync
    
      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run ruff linting
        run: uv run ruff check .
