---
name: Release new version

on:
  push:
    tags:
      - 'v*'

jobs:
  release-version:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Update version from tag
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting version to $VERSION"
          # Update the version in __version__.py
          echo "version = \"$VERSION\"" > src/dbt/adapters/fabric/__version__.py

      - name: Install dependencies
        run: uv sync

      - name: Build and publish package
        run: |
          uv build
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_DBT_FABRIC }}
