---
name: Unit tests
on:
  workflow_dispatch:
  push:
    branches:
      - forked-version
  pull_request:
    branches:
      - forked-version

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run pytest -n auto -ra -v tests/unit
